openapi: 3.0.0
info:
  version: 1.0.0
  title: Health Tracker API
  description: This API provides endpoints for handling CRUD operations on the Health Tracker data.
  contact:
    name: Emma Roche
    email: 20088680@mail.wit.ie
paths:
  /api/users:
    get:
      responses:
        200:
          description: This is a list of the users in the app
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      description: Add a user to the app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: The user has been created

  /api/users/{user-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: This is a specific user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        204:
          description: User has been deleted successfully
    patch:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: User has been updated

  /api/users/email/{email}:
    get:
      parameters:
        - in: path
          name: email
          description: User email path parameter
          required: true
          schema:
            type: string
            example: joe@soap.com
      responses:
        200:
          description: This is a specific user by email in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /api/users/{user-id}/activities:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of activities for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'

  /api/users/{user-id}/healthRecords:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of health records for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthRecord'

  /api/users/{user-id}/sleepTracking:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of sleep tracking entries for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SleepTracking'

  /api/users/{user-id}/moodTracking:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of mood tracking entries for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoodEntry'

  /api/users/{user-id}/weightGoals:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of weight goals for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goals'

  /api/users/{user-id}/fitnessGoals:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of fitness goals for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goals'


  /api/users/{user-id}/nutritionGoals:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: List of nutrition goals for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goals'

  /api/activities:
    get:
      responses:
        200:
          description: List of all activities in the app
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
    post:
      description: Create a new activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        201:
          description: The activity has been created

  /api/activities/{activity-id}:
    get:
      parameters:
        - in: path
          name: activity-id
          description: Activity ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: This is a specific activity in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    delete:
      parameters:
        - in: path
          name: activity-id
          description: Activity ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Activity has been deleted
    patch:
      parameters:
        - in: path
          name: activity-id
          description: Activity ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Activity has been updated

  /api/healthRecords:
    post:
      description: Create a Health Record Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthRecord'
      responses:
        201:
          description: Health Record Entry has been created

  /api/healthRecords/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Health Record Entry ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Health Record Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthRecord'
      responses:
        200:
          description: Health Record Entry has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Health Record Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Health Record Entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthRecord'

    delete:
      parameters:
        - in: path
          name: id
          description: Health Record Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Health Record Entry has been deleted

  /api/sleepTracking:
    post:
      description: Create a Sleep Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SleepTracking'
      responses:
        201:
          description: Sleep Entry has been created

  /api/sleepTracking/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Sleep Entry ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Sleep Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SleepTracking'
      responses:
        200:
          description: Sleep Entry has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Sleep Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Sleep Entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SleepTracking'

    delete:
      parameters:
        - in: path
          name: id
          description: Sleep Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Sleep Entry has been deleted

  /api/sleepTracking/user/{user-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'

        - in: path
          name: userId
          description: User ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get all Sleep Entries for a User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SleepTracking'

  /api/fitnessGoals:
    post:
      description: Create a Fitness Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        201:
          description: Fitness Goal has been created

  /api/fitnessGoals/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Fitness Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Fitness Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        200:
          description: Fitness Goal has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Fitness Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Fitness Goal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goals'

    delete:
      parameters:
        - in: path
          name: id
          description: Fitness Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Fitness Goal has been deleted

  /api/fitnessGoals/{id}/complete:
    put:
      parameters:
        - in: path
          name: id
          description: Fitness Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Mark a Fitness Goal as Completed
      responses:
        200:
          description: Fitness Goal has been marked as completed

  /api/nutritionGoals:
    post:
      description: Create a Nutrition Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        201:
          description: Nutrition Goal has been created

  /api/nutritionGoals/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Nutrition Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Nutrition Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        200:
          description: Nutrition Goal has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Nutrition Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Nutrition Goal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goals'

    delete:
      parameters:
        - in: path
          name: id
          description: Nutrition Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Nutrition Goal has been deleted

  /api/nutritionGoals/{id}/complete:
    put:
      parameters:
        - in: path
          name: id
          description: Nutrition Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Mark a Nutrition Goal as Completed
      responses:
        200:
          description: Nutrition Goal has been marked as completed

  /api/weightGoals:
    post:
      description: Create a Weight Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        201:
          description: Weight Goal has been created

  /api/weightGoals/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Weight Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Weight Goal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goals'
      responses:
        200:
          description: Weight Goal has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Weight Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Weight Goal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goals'

    delete:
      parameters:
        - in: path
          name: id
          description: Weight Goal ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Weight Goal has been deleted

  /api/weightGoals/{id}/complete:
    put:
      parameters:
        - in: path
          name: id
          description: Weight Goal ID path parameter
          required: true
          schema:
            type: integer
      description: Mark a Weight Goal as Completed
      responses:
        200:
          description: Weight Goal has been marked as completed

  /api/moodTracking:
    post:
      description: Create a Mood Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoodEntry'
      responses:
        201:
          description: Mood Entry has been created

  /api/moodTracking/{id}:
    patch:
      parameters:
        - in: path
          name: id
          description: Mood Entry ID path parameter
          required: true
          schema:
            type: integer
      description: Update a Mood Entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoodEntry'
      responses:
        200:
          description: Mood Entry has been updated

    get:
      parameters:
        - in: path
          name: id
          description: Mood Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get a specific Mood Entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoodEntry'

    delete:
      parameters:
        - in: path
          name: id
          description: Mood Entry ID path parameter
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Mood Entry has been deleted

components:
  parameters:
    UserIdPath:
      in: path
      name: user-id
      description: User ID path parameter
      required: true
      schema:
        type: integer
        example: 3232
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 3232
        name:
          type: string
          example: Joe Soap
        email:
          type: string
          example: joe@soap.com
    Activity:
      type: object
      properties:
        id:
          type: integer
          example: 12345
        name:
          type: string
          example: Running
        description:
          type: string
          example: Jogging in the park
    HealthRecord:
      type: object
      properties:
        id:
          type: integer
          example: 5785
        firstName:
          type: string
          example: Emma
        height:
          type: integer
          example: 166
    Goals:
      type: object
      properties:
        id:
          type: integer
          example: 5744
        type:
          type: string
          example: Weight loss goal
    SleepTracking:
      type: object
      properties:
        id:
          type: integer
          example: 5648
        type:
          type: string
          example: Poor
    MoodEntry:
      type: object
      properties:
        id:
          type: integer
          example: 5648
        date:
          type: string
          format: date-time
          example: "2023-12-23T10:30:00"
        mood:
          type: string
          example: "Happy"
        rating:
          type: integer
          example: 5
        notes:
          type: string
          example: "Had a great day!"
        userId:
          type: integer
          example: 2
        sleepId:
          type: integer
          example: 5649